molar_flow_in: List[float],
molar_flow_out: List[float],
catalyst_particle=None,
isothermic_temperature: float = None,
temperature_in_out: dict = None,
refrigerant: AbstractMix = None,
refrigerant_molar_flow: float = None,
refrigerant_temperature_in: float = None,
refrigerant_constant_temperature: bool = False,
refrigerant_flow_arrangement: str = "cocurrent",
exchanger_wall_material: Substance = None,
correlation_heat_transfer: str = "",
isobaric_pressure: float = None,
pressure_in_out: dict = None,
pressure_loss_equation: str = "",
packed_bed_porosity: float = 1