language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
jobs:
  include:
    - python: '3.8' # this is not strictly necessary
      env: EXTRA_TESTS=true
    - python: '3.7'
      env: EXTRA_TESTS=true
script: env $EXTRA_TESTS ./test.py $TEST_SUITE