name: coverage-badge

on:
  - push

jobs:
  coverage-badge:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: coverage.py badge
        uses: tj-actions/coverage-badge-py@v1.8
