name: Codecov
on:
  - push
  - workflow_dispatch
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - name: Install ReactorD
      run: pip install .
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        coverage erase
        pytest tests/ --cov=reactord/ --cov-append --cov-report=term-missing --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
